RentACar/Controllers/CarRental/RentManagersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using RentACar.Models;
using RentACar.Models.CarRental;

namespace RentACar.Controllers.CarRental
{
    [Authorize]
    public class RentManagersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RentManagers/Details/5
        public ActionResult Details()
        {
            var userId = User.Identity.GetUserId();
            var rentManager = db.RentManagers.First(c => c.ApplicationUserId == userId);
            return View(rentManager);
        }
        
        public ActionResult Rented()
        {
            var userId = User.Identity.GetUserId();
            var rentManagerId = db.RentManagers.First(c => c.ApplicationUserId == userId).RentManagerId;
            var rentManager = db.Rents.Where(c => c.RentManagerId == rentManagerId);
            return View(rentManager.ToList());
        }
    }
}

RentACar/Controllers/CarRental/RentsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using RentACar.Models;
using RentACar.Models.CarRental;
using RentACar.Services;

namespace RentACar.Controllers.CarRental
{
    public class RentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        PaymentService _payment = new PaymentService();

        [Authorize(Roles = "Admin")]
        // GET: Rents
        public ActionResult Index()
        {
            var rents = db.Rents.Include(r => r.Car).Include(r => r.RentManager);
            return View(rents.ToList());
        }

        // GET: Rents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rent rent = db.Rents.Find(id);
            if (rent == null)
            {
                return HttpNotFound();
            }
            return View(rent);
        }

        // GET: Rents/Create
        [Authorize]
        public ActionResult Create(int carId)
        {
            var date = DateTime.Now.ToShortDateString();
            ViewBag.DateRent = date;
            return View();
        }

        // POST: Rents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RentId,PriceToPay,Days,DateRent,DateReturn,DaysDiscount,RentsDiscount,Discount,RentAccepted,CarId,RentManagerId")] Rent rent)
        {
            //var errors = ModelState.Values.SelectMany(v => v.Errors);

            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var rentManagerId = db.RentManagers.First(c => c.ApplicationUserId == userId).RentManagerId;
                var car = db.Cars.First(c => c.CarId == rent.CarId);
                
                DateTime date = DateTime.Now;
                rent.DateRent = date;
                TimeSpan days = rent.DateReturn - rent.DateRent;

                car.IsReserved = true;
                rent.Days = days.Days + 1;
                
                rent.RentManagerId = rentManagerId;

                if (rent.DateReturn <= rent.DateRent)
                {
                    return View("InvalidDate");
                }

                db.Rents.Add(rent);
                db.SaveChanges();

                var service = new RentManagerService(db);
                decimal price = service.Price(days.Days + 1, car.PricePerDay);
                service.RentsDiscountHandler(days.Days + 1, rent.RentId, rent.RentManagerId, price);
                return RedirectToAction("RedirectToPayment", new { id = rent.RentId });
            }
            return View("Index");
        }

        [Authorize(Roles = "Admin")]
        // GET: Rents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rent rent = db.Rents.Find(id);
            if (rent == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarId = new SelectList(db.Cars, "CarId", "Name", rent.CarId);
            ViewBag.RentManagerId = new SelectList(db.RentManagers, "RentManagerId", "UserFirstName", rent.RentManagerId);
            return View(rent);
        }

        // POST: Rents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RentId,PriceToPay,Days,DateRent,DateReturn,DaysDiscount,RentsDiscount,Discount,RentAccepted,CarId,RentManagerId")] Rent rent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarId = new SelectList(db.Cars, "CarId", "Name", rent.CarId);
            ViewBag.RentManagerId = new SelectList(db.RentManagers, "RentManagerId", "UserFirstName", rent.RentManagerId);
            return View(rent);
        }

        [Authorize(Roles = "Admin")]
        // GET: Rents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rent rent = db.Rents.Find(id);
            if (rent == null)
            {
                return HttpNotFound();
            }
            return View(rent);
        }

        [Authorize(Roles = "Admin")]
        // POST: Rents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rent rent = db.Rents.Find(id);
            db.Rents.Remove(rent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult RedirectToPayment(int id)
        {
            Rent rent = db.Rents.Find(id);
            ViewBag.Price = rent.PriceToPay;
            ViewBag.Days = rent.Days;
            ViewBag.Discount = rent.Discount;
            if (rent.RentsDiscount)
            {
                ViewBag.DiscountMsg = "Congratulations, you had more than 3 rents in last month, we are giving you real nice 20% discount";
            }
            if (rent.DaysDiscount)
            {
                ViewBag.DiscountMsg = "Congratulations, your rental is longer than a week, we are giving you nice 10% discount";
            }
            return View(rent);
        }

        [HttpPost]
        public ActionResult RedirectToPayment(Rent rents)
        {
            var rent = db.Rents.Where(c => c.RentId == rents.RentId).First();
            var service = new RentManagerService(db);
            if (!service.ReservationTimer(rent.DateRent))
            {
                var car = db.Cars.FirstOrDefault(c => c.CarId == rent.CarId);
                car.IsReserved = false;
                car.IsRented = false;
                rent.RentAccepted = false;
                db.SaveChanges();
                return View("ReservationTimerErr");
            } 
            return RedirectToAction("Payment", new {id = rent.RentId});

        }

        // GET: Payment
        [Authorize]
        public ActionResult Payment(int id)
        {
            Rent rent = db.Rents.Find(id);
            var userId = User.Identity.GetUserId();
            var rentManager = db.RentManagers.First(c => c.ApplicationUserId == userId);

            string url = _payment.CreateUrl(rent.PriceToPay, rent.CarId.ToString(), rent.RentId.ToString(), rentManager.UserFirstName, rentManager.UserLastName, rentManager.User.Email);

            return Redirect(url);
        }

        //POST 
        [HttpPost]
        public ActionResult DotpayConfirm()
        {
            string id = Request["id"];
            string operationNumber = Request["operation_number"];
            string operationType = Request["operation_type"];
            string operationStatus = Request["operation_status"];
            string operationAmount = Request["operation_amount"];
            string operationCurrency = Request["operation_currency"];
            string operationWithdrawalAmount = Request["operation_withdrawal_amount"];
            string operationCommissionAmount = Request["operation_commission_amount"];
            string operationOriginalAmount = Request["operation_original_amount"];
            string operationOriginalCurrency = Request["operation_original_currency"];
            string operationDatetime = Request["operation_datetime"];
            string operationRelatedNumber = Request["operation_related_number"];
            string control = Request["control"];
            string description = Request["description"];
            string email = Request["email"];
            string pInfo = Request["p_info"];
            string pEmail = Request["p_email"];
            string channel = Request["channel"];
            string channelCountry = Request["channel_country"];
            string geoipCountry = Request["geoip_country"];
            string signature = Request["signature"];
            string dotpayPin = _payment.DotpayPin;

            string allParameters = dotpayPin + id + operationNumber + operationType + operationStatus + operationAmount +
                                   operationCurrency + operationWithdrawalAmount + operationCommissionAmount
                                   + operationOriginalAmount + operationOriginalCurrency + operationDatetime +
                                   operationRelatedNumber + control + description + email + pInfo + pEmail + channel +
                                   channelCountry + geoipCountry;
            int controlAsInt = Int32.Parse(control);
            Rent rent = db.Rents.Find(controlAsInt);
            var car = db.Cars.First(c => c.CarId == rent.CarId);

            if (_payment.CheckResponseFromDotpay(signature, allParameters))
            {
                if (operationStatus == "rejected")
                {
                    car.IsReserved = false;
                    car.IsRented = false;
                    rent.RentAccepted = false;
                    db.SaveChanges();
                }
                if (operationStatus == "completed")
                {
                    car.IsReserved = false;
                    car.IsRented = true;

RentACar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using RentACar.Models;

namespace RentACar.Controllers
{
    
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var cars = db.Cars.Where(c => c.IsRented == false).Where(c => c.IsReserved == false);

            return View(cars.ToList());
        }

        public ActionResult Menu()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Send us a message";

            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            ViewBag.Message = "Thanks, we got your message!";

            return PartialView("_ContactThanks");
        }
    }
}

RentACar/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>

<p>Really awesome car rental company with so great looking and professional site.</p>

RentACar/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    F. Tańcula<br/>
    M. Tomczyński<br/>
    Car rental<br/>
    Ulica Sezamkowa<br/>
    <abbr title="Phone">Phone:</abbr>
    666-666-666
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a>
</address>

<div id="formSection">
    <h3>@ViewBag.Message</h3>
    <form method="post" id="contactForm">
        <textarea name="message" id="message" maxlength="150" data-bind="value:message,valueUpdate:'input'"></textarea>
        <input type="submit" value="Send" />
        <span data-bind="text:charactersRemaining"></span> characters remaining
    </form>
    <img src="~/Content/images/wait_progress.gif" id="progress" style="display: none" />
</div>

@*Added setTimeout before function to add some delay*@
@section scripts
{
    <script src="~/Scripts/knockout-3.4.0.js"></script>
    <script>
        function ContactViewModel() {
            var self = this;
            self.message = ko.observable('');
            self.charactersRemaining = ko.computed(function() {
                return 150 - self.message().length;
            });
        }

        ko.applyBindings(new ContactViewModel());
    </script>

    <script>
        $('#contactForm').submit(function () {
            $('#progress').show();
            $.post('', { message: $('#message').val() }).done(function(response) {
                setTimeout(function() { $('#formSection').html(response); }, 2000);
            });
            return false;
        });
    </script>
}

RentACar/Views/Home/Index.cshtml
@using Newtonsoft.Json
@using RentACar.Controllers.CarRental
@model IEnumerable<RentACar.Models.CarRental.Car>
@{
    ViewBag.Title = "Home Page";
}

<h2>Available cars</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <td><strong>Car</strong></td>
            <td><strong>Price per day</strong></td>
            <td><strong>Category</strong></td>
            <td><strong>Description</strong></td>
        </tr>
    </thead>
    <tbody data-bind="foreach:currentCars">
    <tr>
        <td data-bind="text:Name"></td>
        <td data-bind="text:formattedPrice(PricePerDay)"></td>
        <td data-bind="text:Category"></td>
        <td data-bind="text:Description"></td>
        <td>
            <a data-bind="attr: { 'href': '@Url.Action("Create", "Rents")?carId=' + CarId}" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </td>
    </tr>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2">
                <span data-bind="click:previousPage, visible:currentPage() > 1" class="glyphicon glyphicon-circle-arrow-left" style="cursor:pointer;"></span>
                <span data-bind="text:currentPage"></span>
                <span data-bind="click:nextPage, visible:currentPage() < lastPage" class="glyphicon glyphicon-circle-arrow-right" style="cursor:pointer;"></span>
            </td>
        </tr>
    </tbody>
</table>
<script src="~/Scripts/knockout-3.4.0.js"></script>
<script>
    function formattedPrice(priceToPay) {
        var price = priceToPay.toFixed(2)
        return price;
    }

    function carId(id) {
        var car = id;
        return car;
    }

    function ListViewModel() {
        var self = this;

        // properties
        self.cars = @Html.Raw(JsonConvert.SerializeObject(Model, new JsonSerializerSettings {ReferenceLoopHandling = ReferenceLoopHandling.Ignore})); //TODO: embed rents from server as a JSON array
        self.pageSize = 10;
        self.lastPage = Math.ceil(self.cars.length / self.pageSize);
        self.currentPage = ko.observable (1);
        self.currentCars = ko.computed(function(){
            var startIndex = (self.currentPage() - 1) * self.pageSize;
            var endIndex = startIndex + self.pageSize;
            return self.cars.slice(startIndex, endIndex);
        });

        // methods
        self.nextPage = function(){
            self.currentPage(self.currentPage() + 1);
        };
        self.previousPage = function(){
            self.currentPage(self.currentPage() - 1);
        };
    };

    ko.applyBindings(new ListViewModel());
</script>

RentACar/Views/Home/Menu.cshtml
@{
    ViewBag.Title = "Menu";
}

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="@Url.Action("Index", "Home")" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-plus"></span>Rent a car
        </a>
        <a href="@Url.Action("Rented", "RentManagers", new {rentManagerId = ViewBag.RentManagerId})" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-hourglass"></span>Rented cars
        </a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="@Url.Action("Details", "RentManagers")" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-lock"></span>Account
        </a>
        <a href="@Url.Action("Contact", "Home")" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-envelope"></span>Contact
        </a>
    </div>
</div>

RentACar/Views/Home/_ContactThanks.cshtml
<h3>@ViewBag.Message</h3>